version: '2'
services:
  build:
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    volumes:
      - ${PWD}:/workspace
      - ${CACHE_DIR}:/root/.m2
    working_dir: /workspace
    restart: never
