version: '2'
services:
  iupacpackage:
    image: glycoinfo.org:5000/iupac_batch:${IUPAC_VERSION}
    command: echo "iupac package ready"
    volumes:
      - /data
  iupac:
    image: java:8u91-jdk
    working_dir: /data
    command: java -jar iupac-${IUPAC_VERSION}.jar
    volumes_from:
      - iupacpackage
